### ISSUE TITLE
bug: errors:464

### ISSUE THREAD

**Issue by LucasB25** [kyranet/canvas-constructor#446] opened 2022-03-05 18:06 UTC
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in C:\Users\..\Documents\..\node_modules\canvas-constructor\package.json

version: 5.0.2

**Comment by kyranet** [comment] 2022-03-05 20:06
Duplicate of #414.

**Closed by kyranet** 2022-03-05 20:06 UTC
Labels: Bug: Unverified
